### PR TITLE
Add token and login+password authentication

### PR DESCRIPTION
**Pull request by StefH**

### CODE REVIEW

**Comment by david-bugeja** [comment]
If you supply --token only, is there still the need for login and password as well? Still getting the Octokit.NotFoundException on my test repo

**Comment by StefH** [comment]
I did test with `--token xxxxx` only. So --login and --password are not needed in that case.

(I am not able to test login+password because of 2 factor)

**Comment by StefH** [comment]
@david-bugeja Does this version with the `--token` option work correct for you?

**Comment by StefH** [comment]
@david-bugeja If you have time, can you please test this version ? If all works fine, I can release a new Choco.

**Pull request merged**
